apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openui5-fhir-certificate
  namespace: default
spec:
  dnsNames:
    - openui5-fhir.med-united.health
  secretName: openui5-fhir-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openui5-fhir
  labels:
    app: openui5-fhir
spec:
  replicas: 3
  selector:
    matchLabels:
      app: openui5-fhir
  template:
    metadata:
      labels:
        app: openui5-fhir
    spec:
      containers:
      - name: openui5-fhir
        image: 765415433338.dkr.ecr.eu-central-1.amazonaws.com/openui5-fhir:$IMAGE_TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---

kind: Service
apiVersion: v1
metadata:
  name: openui5-fhir
spec:
  selector:
    app: openui5-fhir
  ports:
    - port: 8080

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openui5-fhir
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - openui5-fhir.med-united.health
    secretName: openui5-fhir-tls
  rules:
  - host: openui5-fhir.med-united.health
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: openui5-fhir
              port:
                number: 8080
  
